// TODO: generated by AI

package dau

import (
	"fmt"
	"sync"
	"testing"
	"time"
)

func countFromShards(c *counterImpl) uint64 {
	var total uint64
	for i := range c.shards {
		sh := &c.shards[i]
		withLock(sh.mx.RLocker(), func() {
			total += uint64(len(sh.set))
		})
	}
	return total
}

func TestAddUserSequentialInvariants(t *testing.T) {
	c := NewCounter(4)

	if got := c.Count(); got != 0 {
		t.Fatalf("expected initial Count() == 0, got %d", got)
	}

	if !c.AddUser("alice") {
		t.Fatalf("expected AddUser(alice) to be true on first add")
	}
	if got := c.Count(); got != 1 {
		t.Fatalf("expected Count() == 1, got %d", got)
	}

	if c.AddUser("alice") {
		t.Fatalf("expected AddUser(alice) to be false on second add")
	}
	if got := c.Count(); got != 1 {
		t.Fatalf("expected Count() to stay 1 after duplicate add, got %d", got)
	}

	users := []string{"bob", "carol", "dave"}
	for i, id := range users {
		if !c.AddUser(id) {
			t.Fatalf("expected AddUser(%q) to be true, index=%d", id, i)
		}
	}

	want := uint64(1 + len(users))
	if got := c.Count(); got != want {
		t.Fatalf("expected Count() == %d, got %d", want, got)
	}

	if shardsTotal := countFromShards(c); shardsTotal != want {
		t.Fatalf("shards total = %d; want %d", shardsTotal, want)
	}
}

func TestResetClearsAllState(t *testing.T) {
	c := NewCounter(8)

	for i := 0; i < 1000; i++ {
		_ = c.AddUser(fmt.Sprintf("user-%d", i))
	}

	if c.Count() == 0 {
		t.Fatalf("expected Count() > 0 before Reset()")
	}

	c.Reset()

	if got := c.Count(); got != 0 {
		t.Fatalf("expected Count() == 0 after Reset(), got %d", got)
	}

	for i := range c.shards {
		sh := &c.shards[i]
		withLock(sh.mx.RLocker(), func() {
			if len(sh.set) != 0 {
				t.Fatalf("shard %d is not empty after Reset(): len=%d", i, len(sh.set))
			}
		})
	}
}

func collectIDs(c *counterImpl) map[string]struct{} {
	result := make(map[string]struct{})
	seq := c.ForEach()
	seq(func(id string) bool {
		result[id] = struct{}{}
		return true
	})
	return result
}

func TestForEachSeesAllUsersAndMatchesCount(t *testing.T) {
	c := NewCounter(4)

	ids := []string{"alice", "bob", "carol", "dave", "eve", "alice", "bob"}
	unique := make(map[string]struct{})
	for _, id := range ids {
		unique[id] = struct{}{}
		_ = c.AddUser(id)
	}

	if got := c.Count(); got != uint64(len(unique)) {
		t.Fatalf("expected Count() == %d, got %d", len(unique), got)
	}

	fromIter := collectIDs(c)

	if len(fromIter) != len(unique) {
		t.Fatalf("ForEach saw %d unique ids, want %d", len(fromIter), len(unique))
	}

	for id := range unique {
		if _, ok := fromIter[id]; !ok {
			t.Fatalf("ForEach did not return id %q", id)
		}
	}
}

func TestForEachStopsOnFalseNoDeadlock(t *testing.T) {
	c := NewCounter(2)
	for i := 0; i < 100; i++ {
		_ = c.AddUser(fmt.Sprintf("user-%d", i))
	}

	done := make(chan struct{})

	go func() {
		seq := c.ForEach()
		seq(func(id string) bool {
			return false
		})
		close(done)
	}()

	select {
	case <-done:
	case <-time.After(2 * time.Second):
		t.Fatal("ForEach did not return in time; possible deadlock when yield returns false")
	}
}

func TestConcurrentAddUserCountMatchesUnique(t *testing.T) {
	c := NewCounter(16)

	const goroutines = 64
	const perG = 1000

	var wg sync.WaitGroup
	wg.Add(goroutines)

	allIDs := make([]string, 0, goroutines*perG)
	for g := 0; g < goroutines; g++ {
		for i := 0; i < perG; i++ {
			id := fmt.Sprintf("user-%d", i)
			allIDs = append(allIDs, id)
		}
	}

	for g := 0; g < goroutines; g++ {
		go func(gid int) {
			defer wg.Done()
			for i := 0; i < perG; i++ {
				id := fmt.Sprintf("user-%d", i)
				_ = c.AddUser(id)
			}
		}(g)
	}

	wg.Wait()

	unique := make(map[string]struct{})
	for i := 0; i < perG; i++ {
		id := fmt.Sprintf("user-%d", i)
		unique[id] = struct{}{}
	}

	want := uint64(len(unique))
	got := c.Count()

	if got != want {
		t.Fatalf("concurrent AddUser: Count()=%d, want %d", got, want)
	}

	if shards := countFromShards(c); shards != got {
		t.Fatalf("concurrent AddUser: shards total=%d, Count()=%d", shards, got)
	}
}

func TestNewCounterZeroShardsUsesAtLeastOne(t *testing.T) {
	c := NewCounter(0)

	if len(c.shards) != 1 {
		t.Fatalf("NewCounter(0) should create 1 shard, got %d", len(c.shards))
	}
}
